# PyMOL visualisation of BEB-positive sites (M8 site model).
# Residues numbered by position in the target protein sequence
# (Ensembl translation / UniProt canonical isoform).
# Generated by run_codeml_site_models.py.
load /Users/romainstuder/Github/evosite3d/software/positive_selection_detector/HLA_DQB1/1UVQ.pdb, structure
select target, structure and chain B
hide everything
show cartoon, structure
colour grey70, structure
alter target, resi=str(int(resi)+32)  # align crystal numbering to target protein sequence
rebuild
select sites_BEB95, target and resi 58+89+119
show spheres, sites_BEB95
colour yellow, sites_BEB95
select sites_BEB50, target and resi 41+99+120+235+252+259
show sticks, sites_BEB50
colour orange, sites_BEB50
bg_color white
util.cnc
zoom target
